Ayu-hack/GeeksforGeeks-POTD-Solution

- October 2024/Majority Vote(3 October).java
> Majority Vote(3 October).java

- October 2024/Deletion and Reverse in Circular Linked List(4 Oct).java
> Deletion and Reverse in Circular Linked List(4 Oct).java

- October 2024/Not a subset sum(5 oct).java
> Create Not a subset sum(5 oct).java

- October 2024/Find the number of islands(6 Oct).java
Daily Solution issue #6 solved
> Find the number of islands(6 Oct).java

- October 2024/XOR Linked List(7 oct).cpp
Solve XOR Linked List issue #8
> XOR Linked List(7 oct).cpp

- September 2024/K_sized_subarray_Maximum(27 sept).cpp
Solution is working perfectly for all the test cases..
> Added Potd solution for 27 September 2024

- September 2024/Total Count(29th Sept).py
This is the solution of the Geeks for Geeks, 'Problem of the day' of 29th September 2024 in Python language. Please add `good first issue` and `hacktoberfest` labels.
> Added 'Total Count' Solution of GFG 29th Sept POTD

- Mini Projects/Quote Picker/README.md
- Mini Projects/Quote Picker/index.html
- Mini Projects/Quote Picker/script.js
- Mini Projects/Quote Picker/style.css
Quote picker first project added.
> Add random quote picker!

- September 2024/Alternate_positive_and_negative_numbers(14 Sept).cpp
> Added solution to the POTD of 14 September

- September 2024/Middle_of_linked_list(12 Sept).cpp
> Added Potd Solution for 12 September 

- .vscode/c_cpp_properties.json
- .vscode/launch.json
- .vscode/settings.json
- October 2024/maximumPossibleNumberByBinaryConcatenation.cpp
**Overview**
This PR implements a solution to find the maximum possible number by concatenating the binary representations of integers.
**Key Features**
1). Binary Conversion: Converts integers to their binary forms using bitset.
2). Custom Sorting: Sorts binary strings with a custom comparator to maximize the concatenated result.
3). Edge Case Handling: Returns 0 if all integers are zero.
4). Large Number Support: Utilizes stoll for converting large binary strings to integers.
**Example**
For input {3, 30, 31}, the output is 8191 from concatenating the binary strings 11, 11110, and 11111.
> Implement maxGoodNumber function to find maximum possible number by binary concatenation

- September 2024/KthNearestObstacleQueries.cpp
> Create Leetcode WC-413 September 1st  KthNearestObstacleQueries.cpp

- SDL2project.cpp
- Install SDL2 library.
1. Download SDL2 from SDL2 Downloads.
2. Extract the files and copy the `include` and `lib` folders to your project directory.
3. Add the SDL2 `lib` folder to your compiler's library path and the `include` folder to your compiler's include path.
1. Install SDL2 using Homebrew: ```bash brew install sdl2
1. Initialization and Window Creation:
You correctly initialize SDL and create a window and renderer.
2. Event Handling: 
You handle SDL_QUIT to exit the loop. 
You handle SDL_KEYDOWN to move the rectangle based on key presses.  
You handle SDL_MOUSEMOTION to move the rectangle based on mouse movement.
3. Rendering: 
You set the draw color and clear the renderer. You draw the rectangle and present the renderer.
> Create SDL2 project on Mouse and keyboard Events

- October 2024/8-oct-potd (java-without using sort() )
it is done without using inbuilt sort() (which takes O(NlogN) time complexity) function which takes O(N) time complexity.
> Create 8-oct-potd ( java-without using sort() )

- September 2024/55.JumpGame
Jump Game Question - September Streak
This pull request adds the solution for the "Jump Game" problem as part of the September streak questions. The solution is implemented in [mention the programming language used, e.g., Python, Java, etc.], following the guidelines and constraints provided by the GeeksforGeeks Problem of the Day (POTD). The goal of the Jump Game problem is to determine if you can reach the last index of the array given an initial starting position and the maximum number of steps you can take at each position.
Feel free
ree to adjust any details specific to your implementation.
63563dd-5cca-4547-8854-3a168f1d0fb3)
> Adding Jump Game Question Sept streak question

- Mini Projects/Heath Tool BMI Calculator.py
This project is a **BMI (Body Mass Index)** Calculator built using **Python** and **Tkinter**. It allows users to calculate their BMI based on their **height** (in meters) and **weight** (in kilograms). The application also categorizes the BMI result into various **health ranges** (Underweight, Normal, Overweight, and Obesity) and provides motivational messages for each category to encourage healthy living.
The tool features a user-friendly interface and includes options to reset input values and exit the application.
The project is complete to be used. Please add `hacktoberfest` and `good first issue` labels on it.
> Health Tool: BMI Calculator

- October 2024/Largest_pair_sum(8 Oct).cpp
Modified the code and wrote code that runs in o(n) as asked in the question. The Previous Solution was of O(nlogn) which is slower than o(n).
Kindly Review it and Merge it under the Hacktoberfest2024 tags.
Thank You <3
> Oct 8 GFG POTD

- August 2024/Sorting_Elements_of_an_Array_by_Frequency(28 August).cpp
The solution is working perfectly fine..
> Added POTD for August 28 

- October 2024/maximumProduct.cpp
**Overview**
This PR implements a solution to find the maximum possible product by selecting one element from a given subarray and another element from the remaining part of the array.
**Key Features**
1). Subarray Selection: Iterates through the specified subarray to find the maximum element within the given range [l:r].
2). Remaining Array Selection: Finds the element outside the subarray that maximizes the product with the maximum element from the subarray.
3). Efficient Comparison: Uses loops to ensure both subarray and remaining array elements are compared efficiently.
4). Edge Case Handling: Handles scenarios where there are no valid elements outside the subarray for product computation.
**Example**
For input array {1, 2, 3, 4, 5} and subarray range l = 2, r = 4, the output is 15, …
> Maximum Product : GFG - Weekly contest

- October 2024/Created Linked List Matrix(9th october).java
> Create Created Linked List Matrix(9th october).java

- September 2024/Max sum path in two arrays(1st September).java
> Create Max sum path in two arrays(1st September).java

- October 2024/Largest Pair Sum(8 Oct).py
Solved October 8 POTD in GeekForGeeks using python.
Problem - Given an array find the largest sum of number pair
Ex: Input: [10,5,2,20]
Output: 30 (10+20)
Solution: First sort the array then get the sum of the last 2 integers
> Solved Largest Pair Sum (Oct 8) Using Python

- September 2024/Sort 0s1s2s POTD(9th Sept).py
I added the Solution of the Problem GFG POTD (Sort 0s, 1s, 2s) dated 9th September 2024 in python language. Please review and check the working of the solution.
The screenshot is as follows:
> Added the Solution of the Problem GFG POTD

- September 2024/Sort (0, 1, 2).java
All TestCases Passed with 100% Accuracy!!
> Create Sort (0, 1, 2).java

- October 2024/Linked List Matrix(9 oct).py
Linked List Matrix Solution
Problem:
The task is to convert a 2D matrix into a linked list matrix where each node contains pointers to the right and down nodes, essentially forming a 2D matrix-like structure with linked nodes.
Solution Overview:
This pull request implements a solution for constructing a linked list matrix from a given 2D array. Each element in the matrix is represented by a node, and each node has two pointers: one pointing to the next element on the right and another pointing to the next element below. The solution includes the following:
1. Node Class: Defines the structure of each node with data, right, and down pointers.
2. construct_linked_matrix Function: Takes a 2D array as input and converts it into a linked list matrix by connecting nodes horizontally (right …
> Added Solution POTD OCT 9 using python

- July 2024/Check for BST (24 July).cpp
> Create Check for BST (24 July).cpp

- January 2024/Array Pair Sum Divisibility Problem (1 Jan).cpp
> Create Array Pair Sum Divisibility Problem (1 Jan).cpp

- July 2024/Remove_Duplicates(28 July).cpp
> Added POTD for July 28

- January 2024/Best Time to buy and sell the stock
- January 2024/Spiral Matrix.txt
Best Time to Buy and Sell the stock
> Best time to buy and sell the stock  #12

- January 2024/Spiral Matrix.txt
Adding the Sprial matrix Question from January streek
> Adding Jan streek question leetcode of #12

- July 2024/Remaining_String(16 July).cpp
> Added POTD solution for 16 July.

- October 2024/Max distance between same elements(10th October).java
All Test Cases Passed Successfully !!!
> Create Max distance between same elements(10th October).java

- July 2024/Segregate_0s_and_1s(14 July).cpp
> Added POTD for 14 July.

- July 2024/Linked_list_of_strings_forms_a_palindrome(2 July).cpp
> Added POTD solution for 2nd July.

- January 2024/WordSearch.txt
> Word Search Jan streek Leetcode issue #12 

- April 2024/AddNumLinkedList_30April.java
**Add** Number Linked Lists
Difficulty: Medium Points: 4
Given two numbers, num1, and num2, represented by linked lists. The task is to return the head of the linked list representing the sum of these two numbers.
For example, the number 190 will be represented by the linked list, 1->9->0->null, similarly 25 by 2->5->null. Sum of these two numbers is 190 + 25 = 215, which will be represented by 2->1->5->null. You are required to return the head of the linked list 2->1->5->null.
Note: There can be leading zeros in the input lists, but there should not be any leading zeros in the output list.
**Examples:**
Input: num1 = 45 (4->5->null), num2 = 345 (3->4->5->null)
Output:  3->9->0->null  
**Explanation:** 
For the given two linked list (4 5) and (3 4 5), after adding the two linked list …
> 30 April 2024 problem: Add Number LinkedList in java issue #15

- October 2024/Max distance between same elements(10 oct).cpp
> Create Max distance between same elements(10 oct).cpp

- October 2024/Reorganize The Array(11th October).java
> Create Reorganize The Array(11th October).java

- .vscode/settings.json
- September 2024/Reorganize_The_Array(11 Sept).cpp
> Added POTD solution for 11 September.

- May 2024/You and Your Books(25 May).cpp
Added Solution of POTD 25th of May
Regarding : (Add solution of May 2024. #16)
> Added solution of POTD 25th of May in C++

- Projects Ai-ML/Text Summariser/README
- Projects Ai-ML/Text Summariser/app.py
**Text Summarizer**
The PDF to Text Summarizer feature enables users to generate summaries from uploaded PDFs or text inputs. Developed with Streamlit and Python, it employs the txtai library for text summarization and PyPDF2 for efficient text extraction from PDFs.
**Installation to be done**
pip install streamlit
pip install txtai
pip install PyPDF2
added the screenshot of the above
> Text-Summarizer created and added

- May 2024/geekAndItsGameOfCoins.cpp
**Title : Geek and its Game of Coins**
**Description :** 
This PR adds a dynamic programming solution to the "Geek and its Game of Coins" problem, where players take turns picking x, y, or 1 coin, and Geek plays first. It determines if Geek will win when both play optimally. The PR also includes a driver program that takes inputs for n, x, and y, and outputs whether Geek wins or not.
> Solution for "Geek and its Game of Coins" (29 May)

- October 2024/Two Smallests in Every Subarray(12th October).java
> Create Two Smallests in Every Subarray(12th October).java

- August 2024/Spirally traversing a matrix(1st August).java
> Create Spirally traversing a matrix(1st August).java

- August 2024/Validate an IP Address(6th August).java
Level  - medium
Approach - Naive
> Create Validate an IP Address(6th August).java

- August 2024/N meetings in one room(4th August).java
Level - Easy
Approach - Greedy Algorithm
> Create N meetings in one room(4th August).java

- August 2024/Bottom View of Binary Tree(5th August).java
Level - Medium
Approach - Level Order Traversal, Queue, TreeMap
> Create Bottom View of Binary Tree(5th August).java

- October 2024/Two Smallests in Every Subarray(12 oct).cpp
> Two Smallests in Every Subarray(12 oct).cpp

- September 2024/Two_Smallests_in_Every_Subarray(12 Sept).cpp
> Added Solution to POTD for 12 September.

- October 2024/Delete Alternate Nodes(13th October).java
Level - Easy
Approach - Simple loop, one pass
> Create Delete Alternate Nodes(13th October).java

- July 2024/Construct_Binary_Tree_from_Parent_Array(17 July).cpp
Problem: Construct Binary Tree from Parent Array (17 July)
> Solution of Construct Binary Tree from Parent Array (17 July)

- Multiply two linked lists_(1stOctPOTDgfg)
This code multiplies two numbers represented by linked lists, where each node contains a digit. It calculates the product modulo   10 ^9 + 7
by traversing both lists.
Kindly assign me this.
> Create Multiply two linked lists_(1stOctPOTDgfg)

- Find the number of islands(six oct POTD -GFG)
This C++ code defines a class Solution that implements a depth-first search (DFS) algorithm to count the number of islands in a 2D grid, where '1' represents land and '0' represents water. The numIslands method iterates through the grid, incrementing a counter each time it finds a '1', and uses the DFS function to mark all connected land cells as '0'.
Kindly assign me this.
> Solution Find the number of islands(6 oct POTD -GFG)

- October 2024/Delete Alternate Nodes(13 OCT).java
> Create Delete Alternate Nodes(13 OCT).java

- September 2024/Delete_Alternate_Nodes(13 Sept).cpp
> Added POTD solution for 13 September

- June 2024/GFGPOTD_01_06_2024_odd_even_problem.java
#17 added GF POTD 01-06-2024 in java
> Solution Odd Even Problem (01 July).java

- April 2024/Sum of all substrings of a number(1stApril_POTD_GFG)
This code calculates the sum of all possible substrings of a given number (represented as a string) using dynamic programming to efficiently compute contributions of each digit. The result is returned modulo  to handle large numbers.
Kindly assign me this task.
> Create Sum of all substrings of a number(1stApril_POTD_GFG)

- July 2024/Remove Half Nodes(20 July).cpp
Problem: Remove Half Nodes(20 July)
> Solution Remove Half Nodes(20 July)

- Parenthesis Checker(18 sep GFG-POTD)
> Create Parenthesis Checker(18 sep GFG-POTD)

- Missing And Repeating(23 sep GFG-POTD)
> Create Missing And Repeating(23 sep GFG-POTD)

- May 2024/Odd Even Problem(1st_May_POTD_gfg)
Description: This function determines whether the sum of two counts, x (characters in even positions with even frequency) and y (characters in odd positions with odd frequency), is even or odd, based on the given string.
Kindly assign me this task, as I have implemented the solution that calculates the required sum efficiently.
> Create Odd Even Problem(1st_May_POTD_gfg)

- Majority Vote(3 oct GFG-POTD)
This code defines a class Solution with a method findMajority that identifies elements in a vector nums appearing more than n/3 times, where n is the size of the vector. It uses an unordered map to count occurrences of each element, then collects elements meeting the frequency condition into a result vector, which is sorted before being returned. If no such elements exist, it returns {-1}.
Please assign me this.
> Create Majority Vote(3 oct GFG-POTD)

- Mini Projects/emoji_generator/emoji_gen.py
- Mini Projects/emoji_generator/requirements.txt
Added my mini project!
Random Emoji Generator.
Thankyou ! 
Screenshot of Emoji Generator:
> Added emoji Generator

- March 2024/Peak element(1stMay_POTD_gfg)
This code uses binary search to efficiently find a peak element in an array, where an element is considered a peak if it's greater than or equal to its neighbors.
Kindly assign me this task.
> Create Peak element(1stMarch_POTD_gfg)

- September 2024/Count_Linked_List_Nodes(14 Sept).cpp
> Added POTD solution for 14 September.

- October 2024/Count Linked List Nodes(14 Oct).java
> Solution Count Linked List Nodes(14 Oct).java

- August 2024/11_August_POTD.cpp
Added POTD of 11 August 2024 (Job Sequencing Problem). Review and Merge it under the hacktoberfest tags.
Thank You <3
> Added 11_August_POTD.cpp

- April 2024/Add Number Linked Lists(30April GFG-POTD)
Helper Functions:
addathead(Node* &head, int data): Adds a new node with the given data at the end of the linked list. reverselist(Node* &head): Reverses the linked list. Main Function:
addTwoLists(Node* num1, Node* num2): Adds two numbers represented by linked lists num1 and num2. Reverses both input lists.
Iterates through both lists, adding corresponding digits and managing carry. Adds the resulting digits to a new list.
Reverses the result list before returning it.
This approach ensures that the numbers are added correctly, even if they have different lengths or if there’s a carry at the end.
Please ,assign me this.
> Create Add Number Linked Lists(30April GFG-POTD)

- July 2024/Array to BST(25 july-GFG -POTD)
This C++ code defines a class Solution that converts a sorted array into a balanced Binary Search Tree (BST). Here’s a brief description:
Function solve: This recursive function takes a sorted array nums and constructs a BST. It finds the middle element of the current subarray, makes it the root, and recursively does the same for the left and right subarrays to create left and right subtrees. Function sortedArrayToBST: This function initiates the recursive process by calling solve with the entire array. The result is a balanced BST where the middle element of the array becomes the root, ensuring the tree is height-balanced.
Please assign me this.
> Create Array to BST(25 july-GFG -POTD)

- February 2024/does array represent heap.py
> Solution does array represent heap (17 feb)

- October 2024/Count Linked List Nodes(October 14).cpp
Problem name: Count Linked List Nodes
Added the solution of potd 14-10-2024
> Solution to potd 14-10-2024 in C++

- March 2024/ZigZag Tree Traversal(21march GFG-POTD)
Initialization:
A queue is used to facilitate level order traversal. A bool variable leftToRight is used to keep track of the current traversal direction. Traversal:
For each level, the nodes are processed and their values are stored in a temporary vector ans. The index for storing values in ans is determined by the current traversal direction (leftToRight). After processing all nodes at the current level, the direction is toggled. Result Compilation:
The values from ans are appended to the final result vector result.
Please,assign me this.
> Create ZigZag Tree Traversal(21march GFG-POTD)

- May 2024/Root to Leaf Paths  (8 May GFG-POTD)
This C++ class Solution contains a method to find all root-to-leaf paths in a binary tree. Here’s a brief description:
solve method: This recursive helper function traverses the tree, adding each node’s value to the current path. When a leaf node is reached, the current path is added to the result list. After exploring both left and right subtrees, the function backtracks by removing the last node from the path. Paths method: This function initializes the result list and the current path, then calls the solve method to populate the result list with all root-to-leaf paths. This approach ensures that all paths from the root to the leaves are captured in a list of lists.
Please, assign me this.
> Create Root to Leaf Paths  (8 May GFG-POTD)

- October 2024/Count_Linked_List_Nodes_14_10_24.cpp
I have added the problem of the day of 14 Oct 2024 on GeeksForGeeks. 
I have also included the Driver code (taking input and printing output) so the code can run independently
> Added GeeksForGeeks Problem of the Day for 14 OCT 2024

- April 2024/Party_Of_Couples(10-04-2024)/Question.md
- April 2024/Party_Of_Couples(10-04-2024)/Solution.cpp
Adding the 10th april problm "Party of the Couples.". Do  consider it of merging. Given below is the scrn shot.
Thanks @Ayu-hack !!
> Adding Party_of_couples(10-04-24)

- October 2024/Subarray range with given sum(15 oct).java
> Create Subarray range with given sum(15 oct).java

- Mini Projects/Expense_tracker/Expenses.py
- Mini Projects/Expense_tracker/README.md
- Mini Projects/Expense_tracker/expenses.json
**Issue Number here :**
- #26
**Pull Request Description:**
- Implemented a GUI-based Personal Expense Tracker using Tkinter.
- Added functionalities to input expenses with amount, category, and optional date.
- Integrated a pie chart to visualize expenses by category, using Matplotlib.
- Added a delete option for individual expenses in the Treeview.
- Persisted expenses in a JSON file for data consistency across sessions.
- This PR addresses the basic functionality for tracking and managing personal expenses interactively. 
**Here are images to show the UI :**
> Add Expense Tracker with Pie Chart Visualization (#26)

- March 2024/Print_matrix_in_diagonal_pattern.java
Given a square matrix mat[][] of n*n size, the task is to determine the diagonal pattern which is a linear arrangement of the elements of the matrix as depicted in the following example:
Input:
n = 3
mat[][] = {{1, 2, 3},
{4, 5, 6},
{7, 8, 9}}
Output: {1, 2, 4, 7, 5, 3, 6, 8, 9}
Explaination:
Starting from (0, 0): 1,
Move to the right to (0, 1): 2,
Move diagonally down to (1, 0): 4,
Move diagonally down to (2, 0): 7,
Move diagonally up to (1, 1): 5,
Move diagonally up to (0, 2): 3,
Move to the right to (1, 2): 6,
Move diagonally up to (2, 1): 8,
Move diagonally up to (2, 2): 9
There for the output is {1, 2, 4, 7, 5, 3, 6, 8, 9}.
> Print matrix in diagonal pattern

- March 2024/POTD-GFG-Minimum element in BST.cpp
Given the root of a Binary Search Tree. The task is to find the minimum valued element in this given BST.
Solution for GFG POTD 30th march , minimum element in BST Created
> Create POTD-GFG-Minimum element in BST.cpp

- August 2024/celebrity_problem_3_august.cpp
> Added POTD Solution of august_3

- January 2024/Remove_K_Digits.java
Remove K Digits
Given a non-negative integer S represented as a string, remove K digits from the number so that the new number is the smallest possible.
Note : The given num does not contain any leading zero.
Example 1:
Input:
S = "149811", K = 3
Output: 
111
Explanation: 
Remove the three digits 
4, 9, and 8 to form the new number 111
which is smallest.
Example 2:
Input:
S = "1002991", K = 3
Output: 
21
Explanation: 
Remove the three digits 1(leading
one), 9, and 9 to form the new number 21(Note
that the output must not contain leading
zeroes) which is the smallest.
> Remove K Digits

- October 2024/Two Swaps(16 Oct).cpp
> Two Swaps(16 Oct).cpp

- August 2024/Left View of Binary Tree.cpp
added solution for POTD 23 august 2024 
Left View of Binary Tree
> Create Left View of Binary Tree.cpp

- August 2024/Maximum_Difference.java
Maximum Difference
Given an integer array arr of integers, the task is to find the maximum absolute difference between the nearest left smaller element and the nearest right smaller element of every element in array arr. If for any component of the arr, the nearest smaller element doesn't exist then consider it as 0.
Examples :
Input: arr = [2, 1, 8]
Output: 1
Explanation: left smaller array ls = [0, 0, 1], right smaller array rs = [1, 0, 0]. Maximum Diff of abs(ls[i] - rs[i]) = 1
Input: arr = [2, 4, 8, 7, 7, 9, 3]
Output: 4
Explanation: left smaller array ls = [0, 2, 4, 4, 4, 7, 2], right smaller rs = [0, 3, 7, 3, 3, 3, 0]. Maximum Diff of abs(ls[i] - rs[i]) = abs(7 - 3) = 4
> Maximum_Difference

- October 2024/Count Linked List Nodes(October 14).py
> Count Linked List Nodes Oct-14

- March 2024/Additive_sequence.java
Additive sequence
Given a string n, your task is to find whether it contains an additive sequence or not. A string n contains an additive sequence if its digits can make a sequence of numbers in which every number is addition of previous two numbers (within the range of signed integers). You are required to complete the function which returns true if the string is a valid sequence else returns false. For better understanding check the examples.
Note: A valid string should contain at least three digit to make one additive sequence. 
Example 1:
Input:  
n = "1235813"
Output: 
1
Explanation: 
The given string can be splited into a series of numbers  
where each number is the sum of the previous two numbers: 
1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8, and 5 + 8 = 13. Hence, the output would be 1 …
> Additive_sequence

- April 2024/Remove every k'th node(29 APR GFG-POTD)
The deleteK function in C++ is designed to delete every K-th node from a linked list. Here’s a step-by-step breakdown:
Edge Case Handling: If ( K ) is 1, the function returns NULL since every node would be deleted. Initialization: It initializes a counter cnt to 1, and two pointers, curr (current node) and prev (previous node). Traversal and Deletion:
The function traverses the linked list using a while loop. When the counter cnt equals ( K ), it deletes the current node (curr) and resets the counter to 1. Otherwise, it moves to the next node and increments the counter. Return: Finally, it returns the modified head of the linked list.
please assign me this
> Create Remove every k'th node(29 APR GFG-POTD)

- March 2024/Insert_an_Element _at_the_Bottom_of_a_Stack(4_march_2024).py
Solution for the prolem of the day on 4 march 2024
Swap the array elements
Given an array arr of n positive integers. The task is to swap every ith element of the array with (i+2)th element.
> Swap_the_array_elements(4_march_2024).py

- October 2024/Two_swaps(16th October).cpp
> Created the code file

- July 2024/Closest_Three_Sum.cpp
> Code for Closest_Three_Sum.cpp

- February 2024/Boolean_Parenthesization.cpp
> Code for  Boolean_Parenthesization in cpp

- July 2024/LargestSwap.cpp
> Create LargestSwap.cpp (POTD: 15th July)

- September 2024/Split_Linked_List_Alternatingly(17 Sept).cpp
The solution works perfectly well.
> added solution for POTD 17 September.

- January 2024/Course Schedule(23 jan GFG-POTD)
make_graph: This method creates an adjacency list representation of a graph from a given set of prerequisite pairs. Each pair represents a directed edge from one task to another.
compute_indegree: This method calculates the in-degree (number of incoming edges) for each vertex in the graph.
findOrder: This method determines the order in which tasks should be completed using topological sorting. It starts with vertices that have zero in-degree and processes them, reducing the in-degree of their neighbors. If a neighbor’s in-degree becomes zero, it is added to the queue. The method returns the topological order of tasks or an empty list if a cycle is detected.
Please ,assign me this.
> Create Course Schedule(23 jan GFG-POTD)

- October 2024/Split Linked List Alternatingly     gfg potd 17 oct 24
Given a singly linked list's head. Your task is to complete the function alternatingSplitList() that splits the given linked list into two smaller lists. The sublists should be made from alternating elements from the original list. Note: 
The sublist should be in the order with respect to the original list. Your have to return an array containing the both sub-linked lists. Examples:
Input: LinkedList = 0->1->0->1->0->1
Output: 0->0->0 , 1->1->1
Explanation: After forming two sublists of the given list as required, we have two lists as: 0->0->0 and 1->1->1.
> Create Split Linked List Alternatingly     gfg potd 17 oct 24

- September 2024/Single_Number(18 Sept).cpp
> Added POTD for 18 September.

- July 2024/8_july_gfg_  Search in Rotated Sorted Array_POTD
This function performs a modified binary search on a sorted and rotated array to find the index of the given key. It first checks whether the current mid-element is the key and then determines if the left or right half of the array is sorted, narrowing the search accordingly.
Kindly assign me this
> Create 8_july_gfg_  Search in Rotated Sorted Array_POTD

- May 2024/Minimum steps to destination(12 May GFG POTD).cpp
Given an infinite number line. You start at 0 and can go either to the left or to the right. The condition is that in the ith move, you must take i steps. Given a destination d, find the minimum number of steps required to reach that destination.
Example 1:
Input: d = 2
Output: 3
Explaination: The steps taken are +1, -2 and +3.
Example 2:
Input: d = 10
Output: 4
Explaination: The steps taken are +1, +2, +3 and +4.
> Create Minimum steps to destination(12 May GFG POTD).cpp

- March 2024/Minimum element in BST.cpp
> Create Minimum element in BST.cpp

- October 2024/Nearest multiple of 10(19 Oct).java
> Nearest multiple of 10(19 Oct).java

- February 2024/Recamans sequence( FEB_POTD_GFG_2024)
This function generates the first n elements of Recaman's sequence, ensuring each element is either the difference or sum of the previous element and index i based on specific conditions. It efficiently tracks previously seen elements to maintain uniqueness.
Kindly assign me this task.
> Create Recamans sequence( FEB_POTD_GFG_2024)

- April 2024/Sum of all substrings of a number(4th_April_GFG_POTD)
This function computes the sum of all possible substrings of a given number represented as a string, using dynamic programming to efficiently track contributions from previous substrings. The result is returned modulo  to handle large values.
Kindly assign me this.
> Create Sum of all substrings of a number(4th_April_GFG_POTD)

- April 2024/Find missing in second array(19 APRIL GFG POTD).CPP
Data Structures Used:
unordered_set<int> st: To store elements of array b for quick lookup. vector<int> ans: To store the result, i.e., elements in a but not in b. Steps:
Insert all elements of array b into the unordered set st. Iterate through array a and check if each element is not present in the set st. If an element from a is not found in st, add it to the result vector ans. Return:
The method returns the vector ans containing all elements from a that are missing in b . 
PLEASE ASSIGN ME THIS
> Create Find missing in second array(19 APRIL GFG POTD).CPP

- May 2024/K distance from root( 3 MAY GFG POTD).cpp
This function Kdistance finds all nodes at a distance k from the root of a binary tree. It uses a breadth-first search (BFS) approach with a queue to traverse the tree level by level. Here’s a step-by-step breakdown:
Initialization: A queue q is initialized to store pairs of nodes and their corresponding distances from the root. The root node is pushed into the queue with a distance of 0.
Traversal: The function enters a loop that continues until the queue is empty.
Processing Nodes: For each node, the distance from the root is checked. If the distance equals k, the node’s data is added to the result vector ans.
Adding Children: The left and right children of the current node are added to the queue with their distances incremented by 1.
Return Result: Finally, the function returns the …
> Create K distance from root( 3 MAY GFG POTD).cpp

- June 2024/Maximum occurred integer.py
> Create Maximum occurred integer.py June 7 2024

- May 2024/Longest subsequence-1( 27 MAY GFG POTD)
class Solution {
public:
int solve(int index, int prev, vector<int>& a, vector<vector<int>>& dp) {
if (index == a.size()) {
return 0;
}
if (dp[index][prev + 1] != -1) {
return dp[index][prev + 1];
}
int not_taken = solve(index + 1, prev, a, dp);
int taken = 0;
if (prev == -1 || abs(a[index] - a[prev]) == 1) {
taken = 1 + solve(index + 1, index, a, dp);
}
int ans = max(taken, not_taken);
dp[index][prev + 1] = ans;
return ans;
}
int longestSubseq(int n, vector<int> &a) {
int curr = 0;
int prev = -1;
vector<vector<int>> dp(n, vector<int>(n + 1, -1));
int ans = solve(curr, prev, a, dp);
return ans;
}
};
> Create Longest subsequence-1( 27 MAY GFG POTD)

- October 2024/find_the_sum_of_last_n_nodes_oct23.py
> Find the sum of last n nodes.

- October 2024/Find the Sum of Last N nodes of the Linked List.py
@Ayu-hack Hii 😊
Problem solved : Find the Sum of Last N nodes of the Linked List
> 23 Oct 24  GFG POTD sol.

- September 2024/Palindrome linked list(25 sep) .cpp
- September 2024/Palindrome linkedlist using stack(25 sep).cpp
POTD 25 sep in cpp added successfully. 
using two approaches:
1.) using reverse function and slow & fast pointers
2.) using stack
please take a time to review and merge it.
> Issue #18 has resolved.

- April 2024/Xoring_and_Clearing(14-04-2024)/Count_ways_to_Nth_stair(6-04-2024)/Question.md
- April 2024/Xoring_and_Clearing(14-04-2024)/Count_ways_to_Nth_stair(6-04-2024)/Solution.cpp
@Ayu-hack wanted to contribute to this repo by adding a gfg potd of  14-04-2024.Please consider it for merging. Given below is the image.
> Add Xoring_and_Clearing(14-04-2024)

- February 2024/Reach a Given Score Feb 25 2024.cpp
> Feb 25 2024 Reach a Given Score 

- October 2024/Two Smallests in Every Subarray(Oct 12).py
Solved Two Smallests in Every Subarray(Oct 12) Problem Using Python
> Solved Oct 12 Problem Using Python

- April 2024/Delete Middle of Linked List.java
> solution Delete Middle of Linked List(28 april)

- April 2024/Row with minimum number of 1's.java
> solution Row with minimum number of 1's (22 april)

- October 2024/Modify the Array(oct 24).py
@Ayu-hack Hii 😊
Kindly accept my PR 
pic :
> Modify the Array (24 oct 24) solution of GFG PODT

- October 2024/Modify_the_Array_OCT24.py
This problem was asked on October 24 and is solved using python.
> Modify the Array OCT-24

- October 2024/Alternate_Sorting.cpp
I have added the solution for 25th October and removed my previous pull request for 2 solutions.
> add solution of 25 october issue #47

- October 2024/Alternative Sorting(oct 25).py
> Alternative Sorting (25 oct 24) sol. in py [gfg PODT] 

- October 2024/AlternativeSort.java
Problem-Alternating Sorting 
POTD-25 October 2024
Difficulty-Basic
Language-Java
Sample Example:
Enter the number of elements in the array: 7
Enter the elements of the array:
7 1 2 3 4 5 6
Array after alternate sorting: [7, 1, 6, 2, 5, 3, 4]
Time Complexity-O(nlogn)
Space complexity-O(n)
Explanation: The first element is first maximum and second element is first minimum and so on.
This code has been made as user defined for clear understanding.
> Added Alternating  Sorting question of GFG POTD of 25 Oct 2024 in java

- October 2024/Occurence of an integer in a Linked List(oct 26).py
@Ayu-hack Hii 😊 question solved
pic:
> 26 oct.2024  Occurence of an integer in a Linked List sol. in py of gfg podt

- October 2024/Triplet Family[ 27 oct].py
@Ayu-hack  Hii 😊
today problem solved in python 
pic :
> Triplet Family sol. in py for GFG PODT[27 oct 24]

- October 2024/TripletFamily27Oct.java
Problem- Triplet Family
Difficulty- Basic
Language- Java
Example:
Input: arr[] = [1, 2, 3, 4, 5]
Output: true
Explanation: The pair (1, 2) sums to 3.
Time Complexity- O(n^2)
Space Complexity- O(1)
> Added GFG POTD of 27 Oct 2024 in java

- October 2024/Remove duplicates in array [oct 24].py
@Ayu-hack Hii 😊
gfg PODT sol. in py 
Pic :
> Remove duplicates in array sol. in py of GFG PODT (28 oct 24)

- October 2024/Quick Sort on Linked List.py
> Quick Sort on Linked List  GFG podt sol in py for 29 oct 24

- October 2024/Pairs with difference k( 30 oct ).py
> GFG podt 30 oct 24 -- Pairs with difference k sol. in py

- October 2024/pairs with difference k.py
This question was asked on OCT-30 and is done using python.
> Create pairs with difference k

- October 2024/Pairs with difference k(oct 30).py
Create Pairs with difference k
problem of the day (oct 30)
> Create Pairs with difference k(oct 30).py

- October 2024/Insert in Sorted way in a Sorted DLL( 31 oct 24).py
> GFG podt 31 oct 24 sol. in py

- October 2024/25_Alternating_list.py
this questions was asked on 25 October and the problem is solved using python.
> Alternative Sorting  Oct 25

- October 2024/triplet_family.py
> Triplet family 27 oct

- October 2024/Swap and Maximize(1 nov 24).py
> GFG sol PODT of 1 nov 24 in py

- November 2024/swap_and_maximise_Nov_1.py
this program is done using python.
> Swap and maximize NOV 1

- November 2024/Kth_distance.py
> Kth distance Nov 2

- November 2024/example.py
> solution of 24 nov
